### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by Galad** [specsolutions/deveroom-feedback#1]
Hello,
It would be nice to have support for Visual Studio 2019 since it is released next month.

Thanks

**Comment by gasparnagy** [comment]
Yes, this is a very important next goal.
I will try to fix some stability issues of v1.0.0 and then move onto this.

**Comment by gasparnagy** [comment]
DONE!!!! Go ahead and install it for VS2019!
https://marketplace.visualstudio.com/items?itemName=SpecSolutions.DeveroomVisualStudio2019
