### ISSUE TITLE
Missing Feature: Navigating from a Binding to Steps in Gherkin Files

### ISSUE THREAD

**Issue by LirazShay** [specsolutions/deveroom-feedback#15]
In the original extension we can navigate from code to usage in feature files, if there are many we see list of them

https://specflow.org/documentation/Visual-Studio-Integration-Navigation-Features/

Navigating from a Binding to Steps in Gherkin Files
To navigate from a step definition method to the matching step(s) in your Gherkin feature file(s):

Place your cursor in a step definition method.
Right-click and select Go To SpecFlow Step Definition Usages from the context menu, or press Ctrl+Shift+Alt+S (configurable shortcut).
If only one match exists, the feature file is opened. If more than one matching step is defined in your feature files, select the corresponding feature file from the list to switch to it.

**Comment by gasparnagy** [comment]
Yes, this is on my feature list. Deveroom does not keep a dictionary of all feature file steps in memory, so for this, I need to implement a fast scanning mechanism. This is why this was left out from the first release.

**Comment by LirazShay** [comment]
Sorry but I will wait until this feature will be implemented before continue trying this again, maybe you could do some kind of survey to understand which features are must to have in order that people will agree to leave to good old extension 😥

**Comment by gasparnagy** [comment]
@LirazShay makes sense. Yes, I have been also thinking about the survey... thx.

**Comment by gasparnagy** [comment]
This has been added in v2.1 released just now. Besides navigation from a popup list, you can also choose to get the list into the output window, where it is easier to navigate through a longer list.

@LirazShay I am looking forward to your feedback.
