### ISSUE TITLE
Auto-completion is not working well according to entered phrase

### ISSUE THREAD

**Issue by LirazShay** [specsolutions/deveroom-feedback#16]
I've entered the word 'list' and I see all sentences, including those without the word 'list'

It is very important feature, since steps are globally and the autocompletion is a way to search for matching steps

See attached video
[auto-completion.zip](https://github.com/specsolutions/deveroom-feedback/files/2984165/auto-completion.zip)

https://streamable.com/xazsl

**Comment by LadaVarga** [comment]
Am I doing something wrong as intelisense or autocompletion cannot find anything. I tried clean the solution and rebuild and result is the same I can't see my steps at all. It is not working if I have steps in same solution or If I use external shared steps.

**Comment by gasparnagy** [comment]
@LirazShay thx. yes, this makes sense, I need to add some filtering logic to it.

@LadaVarga Is the navigation working? (If navigation works that means that Deveroom was able to detect the step definitions.) Also it is important to mention that currently the step completion does not pop up automatically, you have to press Ctrl+Space.

**Comment by LadaVarga** [comment]
@gasparnagy Navigation is not working with DEVEROOM, I can't navigate to definition in the same solution. App.config is filled correctly I believe:
`  <specFlow>
    
    <stepAssemblies>
      <stepAssembly assembly="SpecResults" />
      <stepAssembly assembly="Core.Automation.AWS" />
      <stepAssembly assembly="Core.Automation.Shared" />
      <stepAssembly assembly="Core.Automation.SharedSteps" />
    </stepAssemblies>
    <plugins>`

**Comment by gasparnagy** [comment]
@LadaVarga Deverooms saves the log files to the `C:\Users\<youruser>\AppData\Local\Deveroom` folder. There you will find the logs by date.

**Comment by LadaVarga** [comment]
@gasparnagy Looks like deverooms doesn't recognize speflow during discovery. I use Specflow 2.4.0 and VS 2017 the latest one update. I've tried delete specflow files from temp, clean solution and rebuild completely. I can see the colors in the steps but navigation is not possible. One things what we used is we generate feature.cs files by prebuild task (by specflow.exe command), it means we don't need to store feature.cs files in source control.
Deveroom log:
2019-03-21T19:02:36, Verbose, LoadProjectSystem: Loading VsProjectSystem...
2019-03-21T19:02:36, Info, .ctor: Starting Deveroom...
2019-03-21T19:02:36, Info, CreateProjectScope: Initializing project: Core.Automation.Tests
2019-03-21T19:02:37, Info, OnSettingsInitialized: Project settings initialized
2019-03-21T19:02:37, Verbose, .ctor: Creating DeveroomTagger (project: Core.Automation.Tests, SpecFlow: n/a)
2019-03-21T19:02:37, Verbose, SolutionEventListenerOnLoaded: Solution loaded
2019-03-21T19:02:39, Verbose, CheckConfiguration: Checking configuration...
2019-03-21T19:02:39, Verbose, CheckConfiguration: Configuration loaded
2019-03-21T19:02:39, Verbose, GetBindingRegistry: Initial discovery triggered...
2019-03-21T19:02:39, Verbose, RecalculateBindingRegistryInternal: Non-SpecFlow project
2019-03-21T19:02:39, Verbose, Parse: Parsed buffer v1 in 156ms on thread 1
2019-03-21T19:02:49, Verbose, PreExec: Go To Step Definition
2019-03-21T19:02:49, Verbose, PreExec: Go To Step Definition
2019-03-21T19:02:49, Verbose, PreExec: Go To Step Definition

**Comment by gasparnagy** [comment]
@LadaVarga Are you using SpecFlow through NuGet or binary references?

**Comment by LadaVarga** [comment]
@LadaVarga We use Paket + References. Example of reference: C:\!!code\core-automation\packages\SpecFlow\lib\net45\TechTalk.SpecFlow.dll

**Comment by gasparnagy** [comment]
@LadaVarga Does that mean, that you have a `packages.config` file where the SpecFlow package is listed?

**Comment by LadaVarga** [comment]
@gasparnagy No, we use paket.dependecies example:
source http://ourART/artifactory/api/nuget/nuget-3rdParty/
source http://ourART/artifactory/api/nuget/nuget-automation-stable
source http://ourART/artifactory/api/nuget/nugets

nuget SpecFlow  == 2.4.0
nuget SpecFlow.CustomPlugin == 2.4.0
nuget SpecFlow.NUnit == 2.4.0
nuget SpecResults == 0.1.0.7
nuget SpecResults.Json == 0.1.0.7
nuget SpecResults.WebApp == 0.1.0.3

and we've addded Specflow via Add reference -> Browse .dll  stored usually in packages folder-> Select dll.
![2019-03-21 19_43_36-Core Automation - Microsoft Visual Studio](https://user-images.githubusercontent.com/22859476/54777048-bbc64900-4c11-11e9-9960-4ee47d3143c5.png)
](url)

**Comment by gasparnagy** [comment]
@LadaVarga I see. This scenario is not supported yet (#14 tracks it). This seems to be important for more people, so I will try to get a solution for this soon. You need to wait a bit. :(

**Comment by LadaVarga** [comment]
@gasparnagy NP will wait. Thanks a lot for your cooperation

**Comment by gasparnagy** [comment]
@LirazShay your original request has been added in v1.2.
(The issue of @LadaVarga is still open, tracked with #14)

**Comment by gasparnagy** [comment]
@LirazShay thx for the feedback. There are some differences between the models of the two extensions so it is not possible to make it work really the same way (common feedback for the original extension was BTW, that it shows too many items), but points 1) and 4) would definitely be possible and senseful. I will create a separate issue to track those.
