### ISSUE TITLE
.feature.cs files are not re-generated automatically. Have to re-build the project

### ISSUE THREAD

**Issue by z41** [specsolutions/deveroom-feedback#21]
I have to re-build the project in order to get .feature.cs files updated.
My guess that it might be related to async steps in my project (I see "Unable to jump to the step definition. No source location detected" for async steps).

Please, let me know if you need more details. 
VS 2017 v15.9.10, .netcore 2.2 (or 2.3 - not sure).
Extension version is 1.1.1.

**Comment by z41** [comment]
Sorry, I was wrong. Seems like the issue I've been facing is related to file generation. Need further investigation

**Comment by z41** [comment]
Also the feature.cs file is not generated when I add a new feature file.
I might be missing something from the Documentation, but it's all very suspicious and vague to me.
![specflow](https://user-images.githubusercontent.com/2376542/55429891-30e03980-5595-11e9-82e3-3982339c2584.gif)

**Comment by z41** [comment]
Let me know if you want me to upload the demo project. But it's just a default netcore 2.2 xUnit project with specflow libs.

```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="specflow" Version="3.0.188" />
    <PackageReference Include="specflow.tools.msbuild.generation" Version="3.0.188" />
    <PackageReference Include="specflow.xunit" Version="3.0.188" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
```

**Comment by gasparnagy** [comment]
In SpecFlow v3, the generation of the code behind files has been entirely moved to build time using the SpecFlow.Tools.MsBuild.Generation NuGet package, so the fact that the code behind files are only visible after build that's absolutely normal. 

The "Unable to jump to the step definition. No source location detected" error message might be an issue, I check it and get back to you.

**Comment by gasparnagy** [comment]
Ok. The jumping to async step def is a bug. I have created a separate issue #23 for tracking it. 

I close this one as the build-time generation is the by-design behavior in SpecFlow v3.
