### ISSUE TITLE
Error while building the project - Unable to copy file "obj\Debug\..." to "bin\Debug\..."

### ISSUE THREAD

**Issue by ABHIJITHOK** [specsolutions/deveroom-feedback#26]
I am getting the following error while trying to build after opening a .feature file in Visual Studio:

> Unable to copy file "obj\Debug\<ProjectName>.dll" to "bin\Debug\<ProjectName>.dll". The process cannot access the file 'bin\Debug\<ProjectName>.dll' because it is being used by another process.

On killing the processes for deveroom-specflow-v1.exe, and after deleting the bin\debug folder (build configuration is Debug), the project builds successfully. But on opening a .feature file, build fails with the same error as above. 

**My environment:** 
Windows 7 Enterprise
Microsoft Visual Studio Enterprise 2017 version 15.9.10
Application type: .NetFramework Class Library Unit Test Project
I have ensured that the extension "SpecFlow for Visual Studio 2017" is disabled. 

When I change the build configuration to "Release", it builds successfully. 

**Output log from Deveroom:**

> Info: .ctor: Starting Deveroom...
Info: CreateProjectScope: Initializing project: <ProjectName>
Info: OnSettingsInitialized: Project settings initialized
Warning: RecalculateBindingRegistryInternal: Error during binding discovery. 
Command executed:
  <ProjectPath>\<ProjectName>\bin\Debug> C:\USERS\<UserName>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_49D9668A\EXTENSIONS\LJN232NY.HTR\Connectors\V1\deveroom-specflow-v1.exe discovery <ProjectPath>\<ProjectName>\bin\Debug\<ProjectName>.dll <ProjectPath>\<ProjectName>\App.config
Exit code: <not executed>
Message: 
Process C:\USERS\<UserName>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_49D9668A\EXTENSIONS\LJN232NY.HTR\Connectors\V1\deveroom-specflow-v1.exe discovery <ProjectPath>\<ProjectName>\bin\Debug\<ProjectName>.dll <ProjectPath>\<ProjectName>\App.config took longer than 10 min to complete

**Comment by gasparnagy** [comment]
@ABHIJITHOK thx for the error report. It seems that the deveroom discoverer process gets stuck or executes for a very long time. 
Could you please try to run the same process (`<ProjectName>\bin\Debug> C:\USERS<UserName>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_49D9668A\EXTENSIONS\LJN232NY.HTR\Connectors\V1\deveroom-specflow-v1.exe discovery <ProjectName>\bin\Debug<ProjectName>.dll <ProjectName>\App.config`) from a command line and see how long it takes to run?

**Comment by gasparnagy** [comment]
This has been fixed in a way, that if the deveroom-specflow-v1.exe process times out, it is killed, so it will not block the compilation. I have also decreased the timeout to 2 minutes from 10.

**Comment by ABHIJITHOK** [comment]
Thanks @gasparnagy . 
Verified that its executing the tests from Visual Studio Test Explorer as well as from Command Line Interface using dotnet vstest, while using the new Deveroom extension.
Sincere apologies for the delay in my response.
Thanks again.
@ABHIJITHOK
